apiVersion: v1
kind: Service
metadata:
  name: product-inventory
  annotations:
    io.raffa.microsegmentation: 'true'
    io.raffa.microsegmentation.additional-ports: 15000/tcp
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: product-inventory